version: '3'

services:
  server:
    build: .
    container_name: rest-jpg
    restart: always
    user: app
    volumes:
     - ./db:/app/db
     - ./images:/app/images
     - ./https:/app/https:ro
    ports:
      - '443:5000'
      - '80:5001'
