version: '3'

services:
  dev:
    build: .
    container_name: rest
    command: --reset-db
    restart: always
    volumes:
     - ./src:/app/src:ro
     - ./templates:/app/templates:ro
     - ./db:/app/db
    ports:
      - '5000:5000'

  production:
    build: .
    container_name: rest
    command: --prod
    restart: always
    volumes:
     - ./src:/app/src:ro
     - ./templates:/app/templates:ro
     - ./db:/app/db
     - ./https:/app/https:ro
    ports:
      - '443:5000'
