DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS images;

CREATE TABLE users (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	password_hash CHAR(128) NOT NULL
);

CREATE TABLE images (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	owner TEXT NOT NULL,
	FOREIGN KEY (owner) REFERENCES Users (id)
);
