DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS oauth_tokens;

CREATE TABLE users (
	id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	password_hash CHAR(128) NOT NULL
);

CREATE TABLE images (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	owner_id TEXT NOT NULL,
	FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE oauth_tokens (
	token CHAR(128) PRIMARY KEY,
	user_id TEXT NOT NULL,
	scopes TEXT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);
